# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 05:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0003_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(unique=True)),
                ('sub_no', models.IntegerField(blank=True)),
                ('capitalized', models.DateField()),
                ('descr', models.CharField(max_length=32)),
                ('add_descr', models.CharField(blank=True, max_length=256)),
                ('serial', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive'), ('destroyed', 'destroyed'), ('lost', 'lost')], default='active', max_length=32)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Office')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2017, 4, 30, 5, 21, 3, 608806, tzinfo=utc))),
                ('check_type', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=8)),
                ('document', models.FileField(upload_to='assets/')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Staff')),
            ],
        ),
    ]
