# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 07:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20170501_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='descr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.AssetType'),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 1, 7, 2, 37, 370286, tzinfo=utc)),
        ),
    ]
