# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20170501_0702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': (('can_download_assets', 'Can Download Assets'),)},
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 1, 12, 33, 29, 383702, tzinfo=utc)),
        ),
    ]
