# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 11:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20170501_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 3, 11, 58, 11, 283709, tzinfo=utc)),
        ),
    ]
