# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 13:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20170503_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 3, 13, 14, 47, 402142, tzinfo=utc)),
        ),
    ]
