# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 02:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20170504_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 4, 2, 30, 36, 348326, tzinfo=utc)),
        ),
    ]
