# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 03:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_auto_20170504_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.AssetType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='descr',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 4, 3, 34, 1, 230489, tzinfo=utc)),
        ),
    ]
