# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 07:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_auto_20170504_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 4, 7, 18, 41, 755342, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='check',
            name='document',
            field=models.FileField(default=True, upload_to='assets/'),
        ),
    ]
