# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 07:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_auto_20170504_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 4, 7, 28, 21, 552666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='check',
            name='document',
            field=models.FileField(blank=True, upload_to='assets/'),
        ),
    ]
