# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 06:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_auto_20170506_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 6, 6, 49, 40, 921102, tzinfo=utc)),
        ),
    ]
