# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 03:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import jsignature.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rate', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('renew_after_expires', models.BooleanField()),
                ('personal_history', models.FileField(blank=True, null=True, upload_to=b'')),
                ('medical_clearance', models.FileField(blank=True, null=True, upload_to=b'')),
                ('policy_and_conduct', models.FileField(blank=True, null=True, upload_to=b'')),
                ('iom_email', models.BooleanField(default=False)),
                ('basic_field_security', models.FileField(blank=True, null=True, upload_to=b'')),
                ('advanced_field_security', models.FileField(blank=True, null=True, upload_to=b'')),
                ('travel_profile', models.FileField(blank=True, null=True, upload_to=b'')),
                ('proof_of_life', models.FileField(blank=True, null=True, upload_to=b'')),
                ('ses_initiated', models.BooleanField(default=False)),
                ('duty_station_orientation', models.BooleanField(default=False)),
                ('photo', models.FileField(blank=True, null=True, upload_to=b'')),
                ('iom_un_id', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': ' CONTRACTS',
            },
        ),
        migrations.CreateModel(
            name='Contract_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duty_Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JSignatureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', jsignature.fields.JSignatureField(blank=True, null=True, verbose_name='Signature')),
                ('signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Signature date')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_code', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('tor', models.FileField(blank=True, null=True, upload_to=b'')),
                ('start_date', models.DateField()),
                ('expected_need_until', models.DateField(blank=True, null=True)),
                ('expected_monthly_rate', models.IntegerField()),
                ('wbs', models.CharField(max_length=32)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('duty_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Duty_Station')),
            ],
            options={
                'verbose_name_plural': '  POSITIONS',
            },
        ),
        migrations.CreateModel(
            name='Position_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Position Statuses',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt_Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('staff_id', models.CharField(max_length=16)),
                ('personnel_no', models.CharField(max_length=16)),
                ('entry_on_duty', models.DateField(blank=True)),
                ('no_of_dependants', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('home_phone', models.IntegerField(blank=True, null=True)),
                ('mobile_phone', models.IntegerField(blank=True, null=True)),
                ('home_phone_at_station', models.IntegerField(blank=True, null=True)),
                ('mobile_phone_at_station', models.IntegerField(blank=True, null=True)),
                ('address_1', models.CharField(blank=True, max_length=64, null=True)),
                ('address_2', models.CharField(blank=True, max_length=64, null=True)),
                ('address_3', models.CharField(blank=True, max_length=64, null=True)),
                ('address_country', django_countries.fields.CountryField(max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=8, null=True)),
                ('duty_address_1', models.CharField(blank=True, max_length=64, null=True)),
                ('duty_address_2', models.CharField(blank=True, max_length=64, null=True)),
                ('duty_address_3', models.CharField(blank=True, max_length=64, null=True)),
                ('duty_address_country', django_countries.fields.CountryField(max_length=2)),
                ('duty_zip_code', models.CharField(blank=True, max_length=8, null=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Gender')),
                ('shirt_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.Shirt_Size')),
            ],
            options={
                'verbose_name_plural': '   STAFF',
            },
        ),
        migrations.CreateModel(
            name='Staff_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warden_Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Staff_Type'),
        ),
        migrations.AddField(
            model_name='staff',
            name='un_warden_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.Warden_Zone'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='position',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Program'),
        ),
        migrations.AddField(
            model_name='position',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.Position'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Contract_Type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Grade'),
        ),
        migrations.AddField(
            model_name='contract',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Position'),
        ),
        migrations.AddField(
            model_name='contract',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
