# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': (('asset_access', 'Asset Access'), ('procurement_access', 'Procurement Access'), ('hr_access', 'HR Access')), 'verbose_name_plural': '   STAFF'},
        ),
    ]
