# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20170131_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='contract',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
    ]
