# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20170131_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position_status',
            options={'verbose_name_plural': 'Position Statuses'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AddField(
            model_name='position',
            name='staff',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.Staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simple_model',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
