# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20170503_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='duty_address_1',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='duty_address_2',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='duty_address_3',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='duty_address_country',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='duty_zip_code',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='entry_on_duty',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.Gender'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='no_of_dependants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
