# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_auto_20170205_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='action_after_expiration',
        ),
        migrations.AddField(
            model_name='contract',
            name='renew_after_expires',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
