# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_auto_20170504_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='duty_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Office'),
        ),
    ]
