# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_auto_20170504_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
