# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_auto_20170211_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='status',
        ),
        migrations.AddField(
            model_name='position',
            name='notes',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
