# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='report',
            name='report_name',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
