# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170506_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_name',
            new_name='name',
        ),
    ]
