# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20170506_0639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('download_reports', 'Can Download Reports'),)},
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(blank=True, upload_to='reports/'),
        ),
    ]
