# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20170201_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name_plural': ' Contracts'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name_plural': '  Positions'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': '   Staff'},
        ),
        migrations.RenameField(
            model_name='position',
            old_name='expected_need_ntil',
            new_name='expected_need_until',
        ),
    ]
