# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_auto_20170201_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name_plural': ' CONTRACTS'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name_plural': '  POSITIONS'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': '   STAFF'},
        ),
        migrations.AlterField(
            model_name='position',
            name='staff',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hr.Staff'),
        ),
    ]
