# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_auto_20170209_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='staff',
        ),
        migrations.AlterField(
            model_name='contract',
            name='advanced_field_security',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='basic_field_security',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='medical_clearance',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='personal_history',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='policy_and_conduct',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='proof_of_life',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='travel_profile',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='position',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Staff'),
        ),
        migrations.AlterField(
            model_name='position',
            name='tor',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
