# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_auto_20170211_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='staff',
        ),
        migrations.AddField(
            model_name='contract',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.Staff'),
            preserve_default=False,
        ),
    ]
