# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_auto_20170211_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='simple_model_ptr',
        ),
        migrations.RemoveField(
            model_name='contract_type',
            name='simple_model_ptr',
        ),
        migrations.RemoveField(
            model_name='duty_station',
            name='simple_model_ptr',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='simple_model_ptr',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='simple_model_ptr',
        ),
        migrations.RemoveField(
            model_name='position_status',
            name='simple_model_ptr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='simple_model_ptr',
        ),
        migrations.RemoveField(
            model_name='shirt_size',
            name='simple_model_ptr',
        ),
        migrations.RemoveField(
            model_name='staff_type',
            name='simple_model_ptr',
        ),
        migrations.RemoveField(
            model_name='warden_zone',
            name='simple_model_ptr',
        ),
        migrations.AddField(
            model_name='action',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract_type',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract_type',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duty_station',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duty_station',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gender',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gender',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position_status',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position_status',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shirt_size',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shirt_size',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff_type',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff_type',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warden_zone',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warden_zone',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Simple_Model',
        ),
    ]
