# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='sig1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested', to='procurement.JSignatureModel'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='sig2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='need_confirmed', to='procurement.JSignatureModel'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='sig3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funds_available', to='procurement.JSignatureModel'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='sig4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_approval', to='procurement.JSignatureModel'),
        ),
    ]
