# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 01:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_contract_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0002_auto_20170420_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsignaturemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='pr_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.PurchaseRequest'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='pr_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='hr.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='pr_mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='hr.Mission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='pr_requisitioner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requisitioner', to='hr.Staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(default='REQUESTED', max_length=512),
        ),
    ]
