# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_auto_20170421_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='status',
        ),
        migrations.AddField(
            model_name='prstatus',
            name='status',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='sig4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pr_status', to='procurement.JSignatureModel'),
        ),
    ]
