# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_auto_20170422_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pr_status', to='procurement.JSignatureModel'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='sig4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_approval', to='procurement.JSignatureModel'),
        ),
    ]
