# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0005_auto_20170422_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='pr_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
