# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 04:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_purchaserequest_pr_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_date_prepared',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 23, 4, 32, 42, 47035, tzinfo=utc), null=True),
        ),
    ]
