# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 05:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_auto_20170423_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='wbs',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='asset_class',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_date_prepared',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 23, 5, 26, 55, 161955, tzinfo=utc), null=True),
        ),
    ]
