# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 08:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_auto_20170423_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_mission',
            new_name='pr_office',
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_date_prepared',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 23, 8, 50, 16, 510371, tzinfo=utc), null=True),
        ),
    ]
