# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_auto_20170423_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_date_prepared',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 23, 8, 51, 49, 644594, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='hr.Office'),
        ),
    ]
