# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_auto_20170423_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsignaturemodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 23, 10, 9, 6, 804828, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='jsignaturemodel',
            name='pr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='procurement.PurchaseRequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_date_prepared',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 23, 10, 9, 6, 806766, tzinfo=utc), null=True),
        ),
    ]
