# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0024_auto_20170423_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsignaturemodel',
            name='pr',
        ),
        migrations.AlterField(
            model_name='jsignaturemodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 23, 12, 46, 29, 719531, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_date_prepared',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 23, 12, 46, 29, 720553, tzinfo=utc), null=True),
        ),
    ]
