# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_office'),
        ('procurement', '0026_auto_20170427_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='pr_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='program', to='hr.Program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jsignaturemodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 27, 14, 11, 40, 204542, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_date_prepared',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 27, 14, 11, 40, 205738, tzinfo=utc), null=True),
        ),
    ]
