# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 05:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0027_auto_20170427_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsignaturemodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 30, 5, 17, 34, 288412, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_date_prepared',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 30, 5, 17, 34, 289540, tzinfo=utc), null=True),
        ),
    ]
