# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0031_auto_20170501_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsignaturemodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 1, 12, 33, 29, 376790, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_date_prepared',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 1, 12, 33, 29, 377884, tzinfo=utc), null=True),
        ),
    ]
