# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 13:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0033_auto_20170503_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsignaturemodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 3, 13, 14, 47, 389111, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_date_prepared',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 3, 13, 14, 47, 390589, tzinfo=utc), null=True),
        ),
    ]
