# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 02:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0038_auto_20170504_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsignaturemodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 4, 2, 30, 36, 342533, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='pr_date_prepared',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 4, 2, 30, 36, 343586, tzinfo=utc), null=True),
        ),
    ]
